"use client";
import { useRef, useState } from "react";
import { authenticatedFetch } from "@/app/lib/authenticated-fetch";

const ENDPOINT = "/api/internal/easy-mode/recover-claimed-sales";
export default function RecoverClaimedSalesPage() {
  const inFlight = useRef(false); const sent = useRef(false); const [attempted, setAttempted] = useState(false); const [valid, setValid] = useState(false); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [result, setResult] = useState<{ sales: string; run: string } | null>(null);
  async function validateOnly() { if (inFlight.current || sent.current) return; inFlight.current = true; setBusy(true); setValid(false); try { const response = await authenticatedFetch(ENDPOINT, { cache: "no-store" }); const data = await response.json(); if (!response.ok || !data.valid) throw new Error(data.error || "Validation failed safely."); setValid(true); setMessage("Validated: stranded Sales claim is pre-dispatch and the first six tasks are complete."); } catch (error) { setMessage(error instanceof Error ? error.message : "Validation failed safely."); } finally { inFlight.current = false; setBusy(false); } }
  async function recoverOnce() { if (inFlight.current || sent.current || !valid) return; inFlight.current = true; sent.current = true; setAttempted(true); setBusy(true); setValid(false); setMessage("Recovering the pre-dispatch claim and running Sales once…"); try { const response = await authenticatedFetch(ENDPOINT, { method: "POST", headers: { "Content-Type": "application/json" }, body: "{}" }); const data = await response.json(); if (!response.ok) throw new Error(data.error || data.message || "Sales recovery needs attention."); const sales = data.progress?.tasks?.find((task: { label: string }) => task.label === "Sales"); setResult({ sales: sales?.status ?? "Completed", run: data.progress?.runStatus ?? data.state }); setMessage(data.message || "Sales completed."); } catch (error) { setMessage(`${error instanceof Error ? error.message : "Sales recovery needs attention."} This page will not send a second request.`); } finally { inFlight.current = false; setBusy(false); } }
  return <main className="min-h-screen bg-slate-950 px-5 py-12 text-white"><section className="mx-auto max-w-xl rounded-2xl border border-slate-700 bg-slate-900 p-6 sm:p-8"><p className="text-xs font-semibold uppercase tracking-[.2em] text-cyan-300">Boss-only pre-dispatch recovery</p><h1 className="mt-3 text-3xl font-semibold">Recover Sales once</h1><p className="mt-4 text-sm leading-6 text-slate-300">Fixed run 3b5ce170-207e-4762-b285-c4b03aaa61f8. This action cannot select another run or module.</p><div className="mt-7 flex flex-col gap-3 sm:flex-row"><button disabled={busy || attempted} onClick={() => void validateOnly()} className="min-h-12 rounded-lg border border-cyan-400 px-5 font-semibold text-cyan-200 disabled:opacity-40">Validate recovery</button><button disabled={busy || !valid || attempted} onClick={() => void recoverOnce()} className="min-h-12 rounded-lg bg-cyan-400 px-5 font-semibold text-slate-950 disabled:opacity-40">Recover &amp; run Sales once</button></div>{message && <p role="status" className="mt-5 text-sm">{message}</p>}{result && <dl className="mt-6 rounded-xl border border-slate-700 p-4 text-sm"><dt className="text-slate-400">Sales status</dt><dd className="font-semibold">{result.sales}</dd><dt className="mt-3 text-slate-400">Run status</dt><dd className="font-semibold">{result.run}</dd></dl>}</section></main>;
}
