import type { Metadata } from "next";
import { cache } from "react";
import { and, eq } from "drizzle-orm";
import { notFound } from "next/navigation";
import { db } from "@/app/db";
import { businessPublications, businessPublicationVersions } from "@/app/db/schema";
import { validateBusinessSlug, validatePublishedBusinessSnapshot } from "@/app/lib/business-publication";
import { publicAudience, publicBusinessKind, publicCallToAction, publicContact, publicHeroCopy, publicProcess, publicSeoDescription, publicServices, publicServicesSummary, publicSocialLinks, publicStory, publicValuePoints } from "@/app/lib/public-business-presentation";

export const dynamic = "force-dynamic";
const loadPublishedBusiness = cache(async (candidate: string) => {
  const slug = validateBusinessSlug(candidate); if (!slug) return null;
  const [row] = await db.select({ snapshot: businessPublicationVersions.snapshot }).from(businessPublications)
    .innerJoin(businessPublicationVersions, and(eq(businessPublicationVersions.publicationId, businessPublications.id), eq(businessPublicationVersions.versionNumber, businessPublications.currentVersion)))
    .where(and(eq(businessPublications.publicSlug, slug), eq(businessPublications.status, "active"))).limit(1);
  return validatePublishedBusinessSnapshot(row?.snapshot);
});
type Props = { params: Promise<{ slug: string }> };

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const snapshot = await loadPublishedBusiness(decodeURIComponent((await params).slug));
  if (!snapshot) return { title: "Business not found" };
  const title = snapshot.search?.title || snapshot.business.name;
  const description = publicSeoDescription(snapshot);
  return { title, description, robots: { index: true, follow: true }, openGraph: { title, description, type: "website" } };
}

export default async function PublicBusinessPage({ params }: Props) {
  const snapshot = await loadPublishedBusiness(decodeURIComponent((await params).slug)); if (!snapshot) notFound();
  const primary = snapshot.brand?.colours[0] || "#173D32"; const accent = snapshot.brand?.colours[1] || "#E9E4D8";
  const cta = publicCallToAction(snapshot); const contact = publicContact(snapshot); const services = publicServices(snapshot);
  const summary = publicServicesSummary(snapshot); const audience = publicAudience(snapshot); const process = publicProcess(snapshot);
  const values = publicValuePoints(snapshot); const story = publicStory(snapshot); const social = publicSocialLinks(snapshot); const kind = publicBusinessKind(snapshot);
  const heroCopy = publicHeroCopy(snapshot); const offeringLabel = kind.workLabel === "Featured range" ? "Products" : "Services";
  const nav = [{ href: "#home", label: "Home" }, ...(services.length || summary ? [{ href: "#services", label: offeringLabel }] : []), { href: "#work", label: kind.workLabel }, ...(story ? [{ href: "#about", label: "About" }] : []), { href: "#process", label: "Process" }, { href: "#contact", label: "Contact" }];
  const visualLabels = [...services.map((service) => service.title), kind.workLabel, snapshot.business.industry, snapshot.business.name].filter((label): label is string => Boolean(label)).slice(0, 4);
  return <main className="min-h-screen bg-[#FCFBF7] text-[#1B211E]">
    <header className="sticky top-0 z-40 border-b border-black/10 bg-[#FCFBF7]/95 px-5 py-4 backdrop-blur sm:px-10"><div className="mx-auto flex max-w-7xl items-center justify-between gap-5"><a href="#home" className="text-xl font-bold tracking-[-0.03em]" style={{ color: primary }}>{snapshot.brand?.name || snapshot.business.name}</a><nav aria-label="Main navigation" className="hidden items-center gap-6 lg:flex">{nav.map((item) => <a key={item.href} href={item.href} className="text-sm font-semibold opacity-70 transition hover:opacity-100">{item.label}</a>)}</nav><a href="#contact" className="rounded-full px-5 py-3 text-sm font-semibold text-white" style={{ backgroundColor: primary }}>{cta}</a></div><nav aria-label="Mobile navigation" className="mx-auto mt-3 flex max-w-7xl gap-5 overflow-x-auto pb-1 lg:hidden">{nav.map((item) => <a key={item.href} href={item.href} className="shrink-0 text-xs font-semibold opacity-70">{item.label}</a>)}</nav></header>
    <section id="home" className="relative scroll-mt-28 overflow-hidden px-5 py-20 sm:px-10 sm:py-28" style={{ background: `linear-gradient(135deg, ${primary}, ${primary}E8)` }}><div aria-hidden="true" className="absolute -right-20 -top-20 h-80 w-80 rounded-full border border-white/20"/><div className="relative mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-[1.15fr_.85fr]"><div className="text-white"><p className="text-xs font-bold uppercase tracking-[0.24em] opacity-70">{snapshot.business.industry || snapshot.business.name}</p><h1 className="mt-5 max-w-4xl text-5xl font-semibold leading-[.98] tracking-[-0.06em] sm:text-7xl">{snapshot.website?.heroHeadline || snapshot.brand?.tagline || snapshot.business.name}</h1>{heroCopy && <p className="mt-7 max-w-2xl text-lg leading-8 text-white/75">{heroCopy}</p>}<div className="mt-8 flex flex-wrap gap-3"><a href="#contact" className="rounded-full bg-white px-7 py-4 font-semibold" style={{ color: primary }}>{cta}</a>{services.length > 0 && <a href="#services" className="rounded-full border border-white/40 px-7 py-4 font-semibold text-white">Explore our work</a>}</div></div><div className="grid grid-cols-2 gap-4" aria-label="Brand showcase">{visualLabels.map((label, index) => <div key={`${label}-${index}`} className={`flex min-h-36 items-end rounded-[2rem] border border-white/20 p-5 text-lg font-semibold text-white shadow-2xl ${index === 0 ? "col-span-2 min-h-48" : ""}`} style={{ background: `linear-gradient(${125 + index * 20}deg, ${accent}55, #FFFFFF12)` }}>{label}</div>)}</div></div></section>
    {audience.length > 0 && <section className="px-5 py-20 sm:px-10"><div className="mx-auto max-w-7xl"><p className="text-xs font-bold uppercase tracking-[0.22em]" style={{ color: primary }}>{kind.audienceLabel}</p><h2 className="mt-4 max-w-3xl text-4xl font-semibold tracking-[-0.045em] sm:text-5xl">Built around the people we serve.</h2><div className="mt-9 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{audience.map((item) => <article key={item.title} className="rounded-3xl border border-black/10 bg-white p-6 shadow-[0_18px_50px_rgba(20,30,25,.06)]"><h3 className="text-lg font-semibold" style={{ color: primary }}>{item.title}</h3>{item.description && <p className="mt-3 text-sm leading-6 opacity-65">{item.description}</p>}</article>)}</div></div></section>}
    {(services.length > 0 || summary) && <section id="services" className="px-5 py-20 sm:px-10" style={{ backgroundColor: `${accent}88` }}><div className="mx-auto max-w-7xl"><p className="text-xs font-bold uppercase tracking-[0.22em]" style={{ color: primary }}>{kind.workLabel}</p><div className="mt-4 flex flex-col justify-between gap-5 md:flex-row md:items-end"><h2 className="max-w-3xl text-4xl font-semibold tracking-[-0.045em] sm:text-5xl">Services shaped around real needs.</h2>{summary && <p className="max-w-xl leading-7 opacity-65">{summary}</p>}</div>{services.length > 0 && <div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{services.map((service, index) => <article key={service.title} className="group rounded-[2rem] border border-black/10 bg-[#FCFBF7] p-7 transition hover:-translate-y-1 hover:shadow-xl"><span className="text-sm font-bold opacity-35">0{index + 1}</span><h3 className="mt-8 text-2xl font-semibold" style={{ color: primary }}>{service.title}</h3>{service.description && <p className="mt-4 leading-7 opacity-65">{service.description}</p>}<a href="#contact" className="mt-7 inline-flex text-sm font-bold">Enquire <span aria-hidden="true" className="ml-2">→</span></a></article>)}</div>}</div></section>}
    <section id="work" aria-label={kind.workLabel} className="scroll-mt-28 px-5 py-20 sm:px-10"><div className="mx-auto max-w-7xl"><div className="grid gap-5 md:grid-cols-12"><div className="min-h-72 rounded-[2rem] p-8 text-white md:col-span-7" style={{ background: `linear-gradient(145deg, ${primary}, ${accent})` }}><p className="text-xs font-bold uppercase tracking-[0.2em] opacity-70">{kind.workLabel}</p><p className="mt-28 max-w-xl text-3xl font-semibold tracking-[-0.04em]">Thoughtful work, presented with clarity and purpose.</p></div><div className="grid gap-5 md:col-span-5"><div className="min-h-32 rounded-[2rem] border border-black/10 p-7" style={{ backgroundColor: accent }}><p className="font-semibold">A distinctive point of view</p></div><div className="min-h-32 rounded-[2rem] border border-black/10 bg-white p-7"><p className="font-semibold">Made for the way customers choose</p></div></div></div></div></section>
    {values.length > 0 && <section className="px-5 py-20 text-white sm:px-10" style={{ backgroundColor: primary }}><div className="mx-auto max-w-7xl"><p className="text-xs font-bold uppercase tracking-[0.22em] opacity-65">Why work with us</p><div className="mt-8 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{values.map((item) => <article key={item.title} className="rounded-3xl border border-white/15 bg-white/5 p-6"><h3 className="text-xl font-semibold">{item.title}</h3>{item.description && <p className="mt-3 text-sm leading-6 text-white/65">{item.description}</p>}</article>)}</div></div></section>}
    <section id="process" className="px-5 py-20 sm:px-10"><div className="mx-auto max-w-7xl"><p className="text-xs font-bold uppercase tracking-[0.22em]" style={{ color: primary }}>How it works</p><h2 className="mt-4 text-4xl font-semibold tracking-[-0.045em] sm:text-5xl">A clear path from interest to action.</h2><ol className="mt-10 grid gap-4 md:grid-cols-3">{process.map((step, index) => <li key={`${step}-${index}`} className="rounded-3xl border border-black/10 bg-white p-6"><span className="text-sm font-bold" style={{ color: primary }}>{String(index + 1).padStart(2, "0")}</span><p className="mt-5 text-lg font-semibold">{step}</p></li>)}</ol></div></section>
    {story && <section id="about" className="px-5 py-20 sm:px-10" style={{ backgroundColor: `${accent}88` }}><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-[.7fr_1.3fr]"><div><p className="text-xs font-bold uppercase tracking-[0.22em]" style={{ color: primary }}>Our story</p><h2 className="mt-4 text-4xl font-semibold tracking-[-0.045em] sm:text-5xl">Purpose behind the work.</h2></div><p className="whitespace-pre-wrap text-lg leading-8 opacity-70">{story}</p></div></section>}
    {kind.b2b && audience.length > 0 && <section className="px-5 py-16 sm:px-10"><div className="mx-auto max-w-7xl rounded-[2rem] border border-black/10 bg-white p-8 sm:p-12"><p className="text-xs font-bold uppercase tracking-[0.22em]" style={{ color: primary }}>For professional teams</p><h2 className="mt-4 text-3xl font-semibold tracking-[-0.04em]">A capable partner for considered projects.</h2><p className="mt-4 max-w-3xl leading-7 opacity-65">Start a conversation about your requirements, timeline and the right next step.</p></div></section>}
    <section id="contact" className="px-5 py-20 text-center text-white sm:px-10" style={{ backgroundColor: primary }}><div className="mx-auto max-w-4xl"><p className="text-xs font-bold uppercase tracking-[0.22em] opacity-65">Start a conversation</p><h2 className="mt-5 text-4xl font-semibold tracking-[-0.05em] sm:text-6xl">Ready to take the next step?</h2><p className="mx-auto mt-5 max-w-2xl text-lg leading-8 text-white/70">Tell us what you are looking for and we’ll help you find the right way forward.</p><a href={contact.href} className="mt-8 inline-flex rounded-full bg-white px-8 py-4 font-semibold" style={{ color: primary }}>{cta}</a>{contact.label && <p className="mt-5 font-semibold">{contact.label}</p>}{social.length > 0 && <div className="mt-6 flex flex-wrap justify-center gap-4">{social.map((item) => <a key={item.href} href={item.href} rel="noreferrer" className="text-sm font-semibold underline underline-offset-4">{item.label}</a>)}</div>}</div></section>
    <footer className="bg-[#102A23] px-5 py-10 text-white/65 sm:px-10"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-6 sm:flex-row"><div><strong className="text-lg text-white">{snapshot.business.name}</strong>{snapshot.brand?.tagline && <p className="mt-2 max-w-md text-sm">{snapshot.brand.tagline}</p>}</div><nav className="flex flex-wrap gap-5 text-sm">{nav.map((item) => <a key={item.href} href={item.href}>{item.label}</a>)}</nav><p className="text-sm">© {new Date().getUTCFullYear()} {snapshot.business.name}</p></div></footer>
  </main>;
}
